version: '3.8'

x-env: &environment
  environment:
    # Version
    - FLUFFYCOIN_TAG=${FLUFFYCOIN_TAG}
    # Host directory to mount persistent data
    - FLUFFYCOIN_RESOURCE_DIR=${FLUFFYCOIN_RESOURCE_DIR}
    # Database parameters
    - PGDATA=${FLUFFYCOIN_RESOURCE_DIR}/db
    - PGUSER=fluffy
    - PGPASSWORD=fluffy
    - POSTGRES_PASSWORD=fluffy
    - PGPORT=5432
    - PGHOST=postgres # service hostname
    - PGDATABASE=fluffycoin

x-mounted-fs: &mounted-fs
  volumes:
    # Allow writing persistent data to the host as the host user
    - ${FLUFFYCOIN_RESOURCE_DIR}:${FLUFFYCOIN_RESOURCE_DIR}:rw
    - /etc/passwd:/etc/passwd:ro
    - /etc/group:/etc/group:ro

x-network: &network
  networks:
    - fluffynet

networks:
  fluffynet:
    driver: bridge

services:
  fluffycoin:
    image: k8s.gcr.io/pause:3.2
    <<: [*network]
    command: "/pause"

  postgres:
    image: postgres:15-alpine3.18
    <<: [*network, *environment]
    volumes:
      - ${FLUFFYCOIN_RESOURCE_DIR}/db:${FLUFFYCOIN_RESOURCE_DIR}/db:rw
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init-db.sql:ro
    expose:
      - "5432" # Internal API Port

  p2p:
    image: fluffyco.in/p2p:${FLUFFYCOIN_TAG}
    <<: [*network, *environment, *mounted-fs]
    ports:
      - "4643:4643" # API Port
      - "4663:4663" # Event Port

  curator:
    image: fluffyco.in/curator:${FLUFFYCOIN_TAG}
    <<: [*network, *environment, *mounted-fs]
    expose:
      - "1337" # Internal API Port
